# Generated by Django 6.0.4 on 2026-04-18 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymenttarget',
            name='exit_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deploymenttarget',
            name='remote_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='deploymenttarget',
            name='stderr_log',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='deploymenttarget',
            name='stdout_log',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='software',
            name='choco_package_name',
            field=models.CharField(blank=True, default='', help_text='Chocolatey package id, e.g. winrar, googlechrome, 7zip', max_length=200),
        ),
        migrations.AddField(
            model_name='software',
            name='deployment_mode',
            field=models.CharField(choices=[('choco', 'Chocolatey'), ('local', 'Local Installer')], default='choco', help_text='Chocolatey = install via choco. Local = upload installer file.', max_length=10),
        ),
        migrations.AlterField(
            model_name='deploymenttarget',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('connecting', 'Connecting'), ('transferring', 'Transferring'), ('installing', 'Installing'), ('verifying', 'Verifying'), ('success', 'Success'), ('failed', 'Failed')], default='queued', max_length=20),
        ),
        migrations.AlterField(
            model_name='software',
            name='installer_file',
            field=models.FileField(blank=True, null=True, upload_to='installers/'),
        ),
        migrations.AlterField(
            model_name='software',
            name='silent_args',
            field=models.CharField(blank=True, default='', help_text='Silent install arguments, e.g. /S, /quiet /norestart, /VERYSILENT', max_length=500),
        ),
    ]
