# Generated by Django 5.2.6 on 2025-09-15 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='is_online',
        ),
    ]
