# Generated by Django 5.2.6 on 2025-11-05 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_remove_client_is_online'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SSHSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('pid', models.IntegerField()),
                ('listen_host', models.CharField(default='127.0.0.1', max_length=100)),
                ('listen_port', models.IntegerField(default=8022)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ssh_session', to='clients.client')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
