# Generated by Django 4.2.25 on 2025-11-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_sshsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='file_base_path',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='glances_port',
            field=models.PositiveIntegerField(default=61208),
        ),
        migrations.AddField(
            model_name='client',
            name='ssh_password',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='ssh_port',
            field=models.PositiveIntegerField(default=22),
        ),
        migrations.AddField(
            model_name='client',
            name='ssh_private_key_path',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='ssh_username',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sshsession',
            name='listen_host',
            field=models.CharField(default='127.0.0.1', max_length=64),
        ),
        migrations.AlterField(
            model_name='sshsession',
            name='listen_port',
            field=models.PositiveIntegerField(default=8022),
        ),
        migrations.AlterField(
            model_name='sshsession',
            name='pid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
