# Generated by Django 6.0.4 on 2026-04-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_remove_client_file_base_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='mac_address',
            field=models.CharField(blank=True, default='', help_text='e.g. AA:BB:CC:DD:EE:FF — required for Wake on LAN', max_length=17),
        ),
    ]
