# Generated by Django 6.0.4 on 2026-04-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_client_mac_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='auto_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='cpu',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='client',
            name='disk_gb',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='os_version',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='ram_gb',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='vnc_port',
            field=models.PositiveIntegerField(default=5900),
        ),
    ]
