# Generated by Django 6.0.4 on 2026-04-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_client_auto_registered_client_cpu_client_disk_gb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='admin_viewed',
            field=models.BooleanField(default=True),
        ),
    ]
