# Generated by Django 6.0.4 on 2026-04-18 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0005_remove_client_file_base_path'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('process_name', 'Process Name'), ('window_keyword', 'Window Keyword'), ('website_domain', 'Website Domain')], max_length=20)),
                ('value', models.CharField(help_text='Process name, keyword, or domain to flag', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['rule_type', 'value'],
                'unique_together': {('rule_type', 'value')},
            },
        ),
        migrations.CreateModel(
            name='GameAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_ip', models.GenericIPAddressField(protocol='IPv4')),
                ('hostname', models.CharField(blank=True, default='', max_length=100)),
                ('alert_type', models.CharField(choices=[('process', 'Game Process Detected'), ('window_title', 'Gaming Window Title Detected')], max_length=20)),
                ('detected_name', models.CharField(max_length=300)),
                ('process_list', models.TextField(blank=True, default='[]', help_text='JSON array of running processes')),
                ('timestamp', models.DateTimeField(help_text='When the client detected the event')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_alerts', to='clients.client')),
                ('dismissed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dismissed_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['client_ip', 'detected_name', 'received_at'], name='alerts_game_client__188277_idx')],
            },
        ),
    ]
